name: DiscordX
version: 1.0.7
main: org.harrydev.discordx.DiscordX
authors: [ harrydev, Jpuf ]
description: A plugin to link your Minecraft Server to Discord
website: https://harrydev.tech
softdepend: [PlaceholderAPI]
commands:
  discord:
    description: Creates and stores an invite to the discord server
    usage: /discord
    permission: discordx.discord
  discordx:
    description: Sends a Command list in console
    usage: /discordx
    permission: discordx.about
  dxdebug:
    description: Sends a Command list in console
    usage: /dxdebug
    permission: discordx.debug
  dxreload:
    description: Reloads the config and restarts the discord bot
    usage: /dxreload
    permission: discordx.reload
permissions:
  discordx.discord:
    default: true
  discordx.about:
    default: true
  discordx.debug:
    default: op
  discordx.reload:
    default: op
